import RepoCard from "../RepoCard/RepoCard";

import "./RepoList.styles.scss";

type StaticRepo = {
  repo: string;
  image: string;

  description: string;
  technologies: string[];
  stars: number;
  forks: number;
};

const repos: StaticRepo[] = [
  {
    repo: "TestScheduler Platform",
    
    description:
      "Web platform designed to plan, organize, and track automotive validation activities. It allows teams to manage projects, SOPs, A-STEPS, validation activities, and sub-activities through a centralized and collaborative interface. The platform features a multi-role access system and an interactive scheduling calendar developed from scratch with drag & drop, resizing, filtering, period navigation, and PDF export. It also includes real-time tracking and a shared Web Push notification service supporting offline notifications, developed collaboratively with the development team at KPIT.",
     technologies: [
      "Angular",
      "ASP.NET Core",
      ".NET 8",
      "MongoDB",
      "Docker",
      "GitLab CI/CD",
      "Web Push"
    ],
        image: "/assets/test-scheduler.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "Training Center Management Application",

    description:
      "Web application designed to manage the activities of a training center. It allows administrators to manage training programs, students, trainers, registrations, and related information through a centralized interface. The application includes multi-role authentication and secure access to functionalities according to user roles, with communication between the frontend and backend through REST APIs.",
    technologies: [
      "React",
      "Spring Boot",
      "Spring Security",
      "MySQL",
      "REST API",
      "Docker"
    ],
        image: "/assets/training-center.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "Dentaire-Solution",
    description:
      "Web application for managing dental appointments and patient follow-up. It provides dedicated dashboards with statistics and key information for monitoring activities, while role-based access allows secretaries and doctors to access the functionalities relevant to their responsibilities. The application also includes automated email notifications to keep patients informed about their appointments.",
       technologies: [
      "React 18",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MySQL"
    ],
        image: "/assets/dentaire.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "ShopX",
    description:
      "E-commerce web application that allows users to browse and manage products, add items to their shopping cart, and place orders through an intuitive interface. The application provides a complete frontend and backend architecture, with REST APIs handling communication between the Angular interface and the application services.",
     technologies: [
      "Angular",
      "ASP.NET Core",
      "C#",
      "REST API"
    ],
        image: "/assets/ShopX.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "ServiTounsi",
    description:
      "Web platform designed to connect customers with home service providers. Customers can browse available services, submit requests, and manage their profiles, while service providers can present their services and respond to customer requests. The application centralizes interactions between customers and providers through a simple and user-friendly interface.",
    
    technologies: [
      "React.js",
      "ASP.NET Core",
      "C#",
      "REST API"
    ],
        image: "/assets/ServiTounsi.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "Restaurant Website",
    description:
      "Web application designed to showcase a restaurant and its services through an interactive online platform. Visitors can explore the restaurant's menu, discover its services, and access essential information through a clear and user-friendly interface. The application provides a responsive experience and connects the frontend with a backend through REST APIs.",
    
    technologies: [
      "React.js",
      "ASP.NET Core",
      "C#"
    ],
    image: "/assets/Restaurant.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "Medical Imaging Diagnosis Assistance",
    description:
    "AI-powered web application designed to assist in the analysis of medical images. Users can upload medical images through the platform and obtain real-time predictions generated by pre-trained deep learning models. The application integrates and compares models such as ResNet101, DenseNet101, and VGG19 to support image-based diagnostic analysis through an intuitive and responsive interface.",
      technologies: [
      "Python",
      "Django",
      "SQLite",
      "Bootstrap",
      "TensorFlow",
      "Keras",
      "Deep Learning"
    ],
        image: "/assets/Scan.png",

      stars: 0,
    forks: 0,
  },

  {
    repo: "Spa Management Web Application",
    description:
  "Web application designed for spa management at Marhaba Palace Sousse, with a dedicated admin dashboard for creating, managing, and monitoring customer appointments. The platform helps spa staff organize reservations, manage services, and keep track of daily activities through a centralized interface with secure access.",
    technologies: [
      "React",
      "Laravel",
      "PHP",
      "MySQL",
      "JWT"
    ],
        image: "/assets/Spa.png",

      stars: 0,
    forks: 0,
  },
];

export default function RepoList() {
  return (
    <>
      <div className="repos">
        {repos.map((repo) => (
          <RepoCard key={repo.repo} {...repo} />
        ))}
      </div>
    </>
  );
}